pages:
  - name: Home
    hide-desktop-navigation: false
    columns:
      - size: small
        widgets:
          - type: server-stats
            servers:
              - type: local
                name: DEBOCKER
                hide-mountpoints-by-default: true
                mountpoints:
                  /mnt/data:
                    hide: false
          - type: group
            widgets:
              - type: reddit
                subreddit: technology
                show-thumbnails: true
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true
      - size: full
        widgets:
          - type: search
            autofocus: true
            search-engine: google
            new-tab: true
          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Proxmox
                url: 'https://proxmox.rjun.fyi'
                icon: 'di:proxmox'
              - title: Pangolin
                url: 'https://Pangolin.rjun.fyi'
                icon: 'di:pangolin'
              - title: Portainer
                url: 'https://portainer.rjun.fyi'
                icon: 'di:portainer'
              - title: Wiregaurd
                url: 'http://wireguard.local'
                icon: 'di:wireguard'
              - title: Jellyfin
                url: 'https://jellyfin.rjun.fyi'
                icon: 'di:jellyfin'
              - title: Nextcloud
                url: 'http://nextcloud.local'
                icon: 'di:nextcloud'
              - title: Immich
                url: 'http://immich.local'
                icon: 'di:immich'
              - title: Kasm
                url: 'https://kasm.rjun.fyi'
                icon: 'di:kasm'
              - title: Deluge
                url: 'http://deluge.local'
                icon: 'di:deluge'
              - title: HomeAssistant
                url: 'http://homeassistant.local'
                icon: 'di:home-assistant'
              - title: Open-WebUI
                url: 'https://ollama.rjun.fyi'
                icon: 'di:chatgpt'
              - title: IT-Tools
                url: 'http://it-tools.local'
                icon: 'di:it-tools'
              - title: Omni-Tools
                url: 'http://omni-tools.local'
                icon: 'si:conventionalcommits'
              - title: Pi-Hole
                url: 'http://pihole.local/admin'
                icon: 'di:pi-hole'
              - title: Nginx-Proxy-Manager
                url: 'http://nginx.local/'
                icon: 'di:nginx-proxy-manager'
          - type: videos
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw
              - UCR-DXc1voovS8nhAvccRZhg
              - UCBJycsmduvYEL83R_U4JriQ
              - UCHnyfMqiRRG1u-2MsSQLbXA
          - type: bookmarks
            groups:
              - title: General
                links:
                  - title: Gmail
                    url: 'https://mail.google.com/mail/u/0/'
                  - title: Amazon
                    url: 'https://www.amazon.in/'
                  - title: Github
                    url: 'https://github.com/'
              - title: Entertainment
                links:
                  - title: YouTube
                    url: 'https://www.youtube.com/'
                  - title: Prime Video
                    url: 'https://www.primevideo.com/'
                  - title: Disney+
                    url: 'https://www.disneyplus.com/'
              - title: Social
                links:
                  - title: Reddit
                    url: 'https://www.reddit.com/'
                  - title: Twitter
                    url: 'https://twitter.com/'
                  - title: Instagram
                    url: 'https://www.instagram.com/'
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
          - type: calendar
            first-day-of-week: monday
          - type: releases
            cache: 1d
            repositories:
              - glanceapp/glanceapp
              - jellyfin/jellyfin
              - pi-hole/pi-hole
              - open-webui/open-webui
              - wg-easy/wg-easy
              - NginxProxyManager/Nginx-Proxy-Manager
              - portainer/portainer
              - 'dockerhub:homeassistant/home-assistant:stable'

